/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.cpp
 *  subm:  LoopController
 *  model: RELbotSimple
 *  expmt: RELbotSimple
 *  date:  April 11, 2024
 *  time:  12:10:31 AM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.0.12836
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/


